version: "3"
services:
  activemq:
    image: webcenter/activemq:5.14.2
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8161:8161"
      - "61616:61616"
  rabbitmq:
    image: rabbitmq:3.7.4-management
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - "15672:15672"
  mysql:
    image: mysql:5.7.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - "./docker/data/mysql:/var/lib/mysql"
      - "./docker/config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai